language: node_js
node_js:
- '4.2'
install:
- npm install -g bower
- npm install
- bower install
script:
- npm run build
deploy:
  provider: npm
  on: 
    tags: true
  skip_cleanup: true
  email : pawel.gutkowski.1993@gmail.com
  api_key: $NPM_API_KEY